# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b772af6b749682ec02581b3a2897d8061f6e891d995ffef15e5df986a79ce906b6844aff43bcc2b18452cee64767aba409f5bff32810890fb4dd4be770dd12a

test:
  secret_key_base: 1aae4796dd0146f7eab66868dbc6b317b3d305ba5cf87d6fdacbd784ea34a6e412c5e514ebfd415882dac62dc7de95f2f94397651851a9b5a2041ece03dd4aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
